### ISSUE TITLE
Create install scripts

### ISSUE THREAD

**Issue by mgmacias95** [googleinterns/step242-2020#19]
There will be three machines in our project:
* One for the wazuh manager
* One for the Elastic Stack
* One for the wazuh agent

Create three separate installation scripts for any of them. These scripts need to be integrated in the terraform developed in #18.

Follow https://documentation.wazuh.com/3.13/installation-guide/index.html

**Comment by niedziol** [comment]
Shouldn't this issue be in another repository?
